name: VisantaraCrates
version: '${project.version}'
main: me.bintanq.visantaracrates.VisantaraCrates
api-version: '1.20'
description: Custom crate plugin for Visantara server.
authors: [ bintanq ]

softdepend:
  - PlaceholderAPI
  - MMOItems
  - ItemsAdder
  - Oraxen
  - Vault
  - Nexo

commands:
  visantaracrates:
    description: VisantaraCrates main command
    aliases: [ vc, crates, crate, qc ]
    usage: /vc <subcommand>
    permission: visantaracrates.use
  cratesmigrate:
    description: Migrate virtual keys from phoenix database to physical crates
    aliases: [ keymigrate, vcmigrate ]
    usage: /cratesmigrate
  cratesmigrateadmin:
    description: Migrate other player's virtual keys to physical crates (Admin only)
    usage: /cratesmigrateadmin <player>
    permission: visantaracrates.admin


permissions:
  visantaracrates.admin:
    description: Full admin access
    default: op
    children:
      visantaracrates.key.give: true
      visantaracrates.massopen: true
      visantaracrates.preview: true
      visantaracrates.use: true
      visantaracrates.bypasscooldown: true
      visantaracrates.bypasslimit: true
      visantaracrates.migrate: true
  visantaracrates.use:
    description: Can use crate
    default: true
  visantaracrates.key.give:
    description: Give key to other
    default: op
  visantaracrates.massopen:
    description: Mass open crate
    default: true
  visantaracrates.bypasscooldown:
    description: Bypass crate cooldown
    default: op
  visantaracrates.bypasslimit:
    description: Bypass lifetime open limit
    default: op
  visantaracrates.migrate:
    description: Migrate old virtual keys
    default: true